# Enable the DISCO operator.
enabled: false

image:
  repository: sapcc/disco
  tag: v201903291718

rbac:
  create: false
  serviceAccountName: default

# Enable debug logging.
debug: false

# Port to expose metrics on.
metricPort: 9091

# TTL for the recordsets.
recordsetTTL: 1800

# Only an ingress' with this annotation will be considered.
ingressAnnotation: "disco"

# Record which should be used. e.g.: 'ingress.domain.tld.' .
record: #DEFINED-IN-SECRETS

# Enable the OpenStack seed for the service user described in the openstack section below.
seed:
  enabled: false

# Credentials of the service user who creates the recordsets in OpenStack Designate.
openstack:
  # authURL:            DEFINED-IN-SECRETS
  # regionName:         DEFINED-IN-SECRETS
  # username:           DEFINED-IN-SECRETS
  # userDomainName:     DEFINED-IN-SECRETS
  # password:           DEFINED-IN-SECRETS
  # projectName:        DEFINED-IN-SECRETS
  # projectDomainName:  DEFINED-IN-SECRETS
  # the name of the zone in which the record should be created
  # zoneName:           DEFINED-IN-SECRETS
