{{- if .Values.maia.enabled }}
apiVersion: v1
kind: ConfigMap

metadata:
  name: maia

data:
  policy.json: |
{{ .Files.Get "files/policy.json" | indent 4 }}
  maia.conf: |
{{ include "maia/templates/etc/_maia.conf" . | indent 4 }}
{{- end }}
