{{- if .Values.prometheus.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.prometheus.persistence.name | quote }}
  labels:
    app: prometheus
    type: maia
spec:
  accessModes:
    - {{ .Values.prometheus.persistence.access_mode | quote }}
  resources:
    requests:
      storage: {{ .Values.prometheus.persistence.size | quote }}
{{- end }}
