apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-maia

data:
  prometheus.yaml: |
    global:
      scrape_timeout: 55s

    scrape_configs:
{{- include "maia/templates/etc/_maia_scrape_config.yaml.tpl" . | indent 6 }}

  maia_scrape_config.yaml: |
{{ include "maia/templates/etc/_maia_scrape_config.yaml.tpl" . | indent 4 }}
