global:
  # region: DEFINED-IN-REGION-SECRETS
  # domain: DEFINED-IN-REGION-SECRETS
  # imageRegistry: DEFINED-IN-REGION-SECRETS
  clusterType: controlplane

maia:
  # maia is on in all regions by default
  enabled: True
  # vice_president is used by default to generate certs
  vice_president: true
  # endpoint_host_public: DEFINED-IN-REGION-SECRETS
  endpoint_port_public: 443
  endpoint_protocol_public: https
  docker_repo: DEFINED-IN-REGION-SECRETS
  image_version: '20190313100650'
  debug: "0"
  listen_port: 9091
  # how long will label values be listed by the API (keep minimal)
  label_value_ttl: "24h"
  # how long are tokens cached before being revalidated
  token_cache_time: "900s"
  # which domain will be assumed for a user if it is not specified via @
  default_domain: monsoon3
  service_user:
    name:  maia
    # password: DEFINED-IN-REGION-SECRETS
    user_domain_name:    Default
    project_name:        service
    project_domain_name: Default
  resources:
    # reasonable defaults, should be reduced for small regions
    memory:
      expected: 100Mi
      tolerated: 1Gi
    cpu:
      # currently maia is used by very few concurrent users
      expected: "10m"
      tolerated: "500m"

# this is the new reused prometheus
prometheus-server:
  image:
    repository: prom/prometheus
    tag: v2.8.0

  name: maia-oprom

  retentionTime: 30d

  additionalScrapeConfigs:
    name: maia
    key: maia_scrape_config.yaml

  ingress:
    enabled: true
    host: maia-prometheus-collector

  # Store on disk
  persistence:
    enabled: true
    # there are not RWO volumens in controlplane
    accessMode: ReadWriteMany
    size: 300Gi
  rbac:
    create: false

  serviceAccount:
    create: false
    name: default

  # The log level of the Prometheus.
  logLevel: debug

  # Kubernetes resource requests and limits for this Prometheus.
  # Flagship configuration for now.
  resources:
    requests:
      cpu: 2
      memory: 8Gi
    limits:
      cpu: 4
      memory: 16Gi

# this is the old homegrown prometheus
prometheus:
  enabled: True
  vice_president: true
  image:
    repository: prom/prometheus
    tag: v2.5.0
  retention: 30d
  listen_port: 9090
  configmap_reload:
    image:
      repository: jimmidyson/configmap-reload
      tag: v0.2.2
  persistence:
    name: data-prometheus-maia-0
    # this should be ReadWriteOnce but change is not possible
    access_mode: ReadWriteMany
    size: 100Gi
  resources:
    # reasonable defaults, should be reduced for small regions
    memory:
      expected: 4Gi
      tolerated: 8Gi
    cpu:
      expected: 0.25
      tolerated: 4

snmp_exporter:
  listen_port: 9116
  image_version: "v0.4.0"
#  docker_repo: DEFINED-IN-REGION-SECRETS
  enabled: False
# the below is as well DEFINED-IN-REGION-SECRETS
#  maia_snmp_config:
#    - name: somename
#      stilltocome: somevalues

jumpserver:
   image:
      namespace: monsoon
      name: jumphealth
      tag: 1.3
#   radius_secret: DEFINED-IN-REGION-SECRETS
   port_number: 9150
