chartmuseum:
  enabled: true

  image:
    repository: sapcc/chartmuseum
    tag: v0.8.0-storage

  persistence:
    enabled: false

  ingress:
    enabled: true
    annotations:
      vice-president: "true"
      disco: "true"

    # Defined in secrets.
    hosts:
      - name: "charts.tld"
        tls: true
        tlsSecret: tls-charts.tld

  env:
    open:
      DISABLE_API: false
      DISABLE_METRICS: false
      STORAGE: "openstack"
      # Defined in secrets.
      # OS_AUTH_URL:
      # OS_PROJECT_NAME:
      # OS_DOMAIN_NAME:
      # OS_USERNAME:
      # OS_PASSWORD:
      # STORAGE_OPENSTACK_CONTAINER:
      # STORAGE_OPENSTACK_REGION:

# Seed OpenStack user and Swift container.
seed:
  enabled: false
  # Defined in secrets.
  #  openstack:
  #    authURL:
  #    regionName:
  #    username:
  #    userDomainName:
  #    password:
  #    projectName:
  #    projectDomainName:
  #    containerName:
