{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "wham.fullname" . }}
  labels:
    app: {{ include "wham.name" . }}
    chart: {{ include "wham.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

data:
  wham.yaml: |
    handlers:
      - "baremetal"
{{- end }}