{{- if .Values.global.dbPassword }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cinder-db-init
  labels:
    system: openstack
    type: configuration
    component: database

data:
  db-init.sql: |
    CREATE DATABASE {{.Values.dbName}};
    CREATE ROLE {{.Values.global.dbUser}} WITH ENCRYPTED PASSWORD '{{required ".Values.global.dbPassword is missing" .Values.global.dbPassword}}' LOGIN;
    GRANT ALL PRIVILEGES ON DATABASE {{.Values.dbName}} TO {{.Values.global.dbUser}};
{{- end }}
