{{- if .Values.global.dbPassword }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cinder-db-maintain
  labels:
    system: openstack
    type: configuration
    component: database

data:
  db-maintain.sql: |
    ALTER ROLE {{.Values.global.dbUser}} WITH ENCRYPTED PASSWORD '{{required ".Values.global.dbPassword is missing" .Values.global.dbPassword}}';
    ALTER ROLE {{ .Values.postgresql.postgresUser }} WITH ENCRYPTED PASSWORD '{{ .Values.postgresql.postgresPassword }}';
{{- end }}
