{{- if .Values.alertmanagers }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "prometheus.name" . }}-alertmanager-config
  labels:
    prometheus: {{ include "prometheus.name" . }}

data:
  config.yaml: |
    - static_configs:
        scheme: https
        timeout: 10s
        - targets:
{{ toYaml .Values.alertmanagers | indent 12}}
{{- end -}}
